### ISSUE TITLE
Null pointer thrown due to underlying adyen-java-api-library

### ISSUE THREAD

**Issue by alexwalkerinfo** [Adyen/adyen-hybris#323]
I'm in the processing of upgrading our version of this plugin to the latest released (11.2.0) and I've come across this issue when the fraud report is stored to hybris.

**Describe the bug**
After processing a payment, the plugin is creating FraudReportModel instances using the PaymentsResponse in DefaultAdyenOrderService:createFraudReportFromPaymentsResponse. A null pointer exception is thrown on line 78 because all instances of FraudCheckResult are null.

` java.lang.NullPointerException: Cannot invoke "com.adyen.model.FraudCheckResult.getAccountScore()" because "fraudCheckResult" is null
	at com.adyen.v6.service.DefaultAdyenOrderService.createFraudReportFromPaymentsResponse(DefaultAdyenOrderService.java:78) ~[classes/:?]
	at com.adyen.v6.service.DefaultAdyenOrderService.storeFraudReportFromPaymentsResponse(DefaultAdyenOrderService.java:121) ~[classes/:?]
	at com.adyen.v6.service.DefaultAdyenOrderService.lambda$updateOrderFromPaymentsResponse$1(DefaultAdyenOrderService.java:182) ~[classes/:?]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.3.27.jar:5.3.27]
	at com.adyen.v6.service.DefaultAdyenOrderService.updateOrderFromPaymentsResponse(DefaultAdyenOrderService.java:180) ~[classes/:?]
	at com.adyen.v6.facades.impl.DefaultAdyenCheckoutFacade.createOrderFromPaymentsResponse(DefaultAdyenCheckoutFacade.java:590) ~[classes/:?]
	at com.adyen.v6.facades.impl.DefaultAdyenCheckoutFacade.createAuthorizedOrder(DefaultAdyenCheckoutFacade.java:570) ~[classes/:?]
	at com.adyen.v6.facades.impl.DefaultAdyenCheckoutFacade.componentPayment(DefaultAdyenCheckoutFacade.java:499) ~[classes/:?]`

I have traced this back to the fact that the Java modelling (utilising jackson) in the recommended adyen-java-api-library (v18.1.3) doesn't reflect the version of the Adyen API that is being used.

For instance check version 67:
https://docs.adyen.com/api-explorer/Checkout/67/post/payments/details

In the 'results' property of 'fraudResult' there is a 'FraudCheckResult' object. 

![Screenshot 2023-10-19 at 12 58 50](https://github.com/Adyen/adyen-hybris/assets/31357740/b6c7c95e-91cb-4d82-91ca-0d3cbd09295a)

Then check version 69 which is used in the v18.1.3 adyen-java-api-library:

![Screenshot 2023-10-19 at 12 59 14](https://github.com/Adyen/adyen-hybris/assets/31357740/d1c722e7-633f-4d4d-82ca-5172d205f99a)

The 'FraudCheckResult' object is now gone.

The problem is that in the Java the FraudCheckResultContainer class is still expecting this structure, and therefore the data is not loaded in correctly. This results in the above null pointer issue, where the FraudCheckResult objects are all null.

I guess the problem is in the version of adyen-java-api-library that is recommended for use in this plugin. I haven't tried later versions yet, but I suspect it won't be a drop in change without refactoring. 

**To Reproduce**
1. Attempt to complete a card payment with fraud reporting turned on for the account
2. Exception is thrown storing the fraud report

**Expected behavior**
No null pointer exception is thrown.

**Comment by prolific8** [comment]
I am also experiencing this issue when implementing version 11.2.0. 

Old structure:
<img width="400" alt="image" src="https://github.com/Adyen/adyen-hybris/assets/25196294/9d78fa49-a196-4ed4-9796-90e32b19dc76">

New structure:
<img width="374" alt="image" src="https://github.com/Adyen/adyen-hybris/assets/25196294/ce30d4af-e23a-4ca9-9736-84c3369080ec">

I am going to attempt downgrading the adyen-java-api-library to a previous version, but I'm unsure if this will have any unintended consequences for newer functionality?

**Comment by kpieloch** [comment]
Fix will be provided in v12.0.0 with upgrade of adyen-java-api-library to version 24.0.0
